// <auto-generated />
namespace SuperMarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTableSupplyOperations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableSupplyOperations));
        
        string IMigrationMetadata.Id
        {
            get { return "202005151938251_addTableSupplyOperations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
